mutation CreateLocation($location: GqlCreateLocationInputType!) {
  createLocation(location: $location) {
    id
  }
}

mutation UpdateLocation($location: GqlUpdateLocationInputType!) {
  updateLocation(location: $location) {
    status
  }
}
query GetLocation($id: UUID!) {
  getLocation(id: $id) {
      id
      code
      name
      isActive
      address {
        country {
          id
          name
        }
        postCode
        city
        address
      }
      area {
        id
        code
        name
      }
      brands {
        id
        code
        isWorkshopDefault
      }
  }
}
