query GetVehicle($id: UUID!) {
  getVehicle(id: $id) {
    id
    vin
    licencePlate
    brand
    model
    type
    status
    firstRegistration
    customerRegistration
    mileage
    modelNumber
    areTyresStored
    nextMainInspection
    nextEmissionsTest
    drivers {
      id
      salutation
      title
      name
      name2
      name3
      countryCode
      postCode
      city
      address
      address2
      birthdate
      salespersonCode
      serviceAdvisor {
        id
        name
      }
      phones {
        contactType
        deviceType
        phone
      }
      emails {
        contactType
        email
      }
    }
    serviceHistory {
      number
      date
      positions {
        name
        description
      }
    }
  }
}
