scalar UUID

schema {
  query: Query
  mutation: Mutation
}

type Query {
  getWorkshopAppointmentAdditionalBusinessStatus(id: UUID!): GqlAdditionalBusinessStatusObjectType!
  getWorkshopAppointmentAdditionalBusinessStatuses: GqlGetAdditionalBusinessStatusesObjectType!
  getLocationWorkshopAppointmentBusinessStatuses(id: UUID!): GqlGetLocationBusinessStatusesObjectType!
  getLocationWorkshopAppointmentAdditionalBusinessStatuses(id: UUID!): GqlGetAdditionalBusinessStatusesObjectType!
  getAvailabilityColors: GqlGetAvailabilityColorsObjectType!
  getWorkshopConnectedLocations(locationId: UUID!): GqlGetWorkshopConnectedLocationsObjectType!
  getLocationOverbooking(locationId: UUID!): GqlGetLocationOverbookingObjectType!
  getLocationWorks(locationId: UUID!): GqlGetLocationWorksObjectType!
  getQualifications: GqlGetQualificationsObjectType!
  getWorkshopLocationWork(id: UUID!): GqlGetWorkshopLocationWorkObjectType!
  getLocationCounter(locationId: UUID!): GqlGetLocationCounterObjectType!
  getLocationCounterCalendar(locationId: UUID!): GqlGetLocationCounterCalendarObjectType!
  getLocationTeamsCalendar(
    locationId: UUID!
    startDate: String!
    endDate: String!
  ): GqlGetLocationTeamsCalendarObjectType!
  getTeamCapacity(id: UUID!, startDate: String!): GqlGetTeamCapacityObjectType!
  getUserPermissions(id: UUID!): GqlGetUserPermissionsObjectType!
}

type Mutation {
  createAdditionalBusinessStatuses(
    additionalBusinessStatuses: [GqlCreateAdditionalBusinessStatusesInputType!]!
  ): GqlCreateAdditionalBusinessStatusesObjectType!
  createWorkshopConnectedLocations(
    locationId: UUID!
    connectedLocationId: UUID
  ): GqlCreateWorkshopConnectedLocationsObjectType!
  updateWorkshopAppointmentAdditionalBusinessStatus(
    additionalBusinessStatus: GqlEditAdditionalBusinessStatusInputType!
  ): GqlEditAdditionalBusinessStatusObjectType!
  activateWorkshopAppointmentAdditionalBusinessStatus(id: UUID!): GqlActivateAdditionalBusinessStatusObjectType!
  deactivateWorkshopAppointmentAdditionalBusinessStatus(
    id: UUID!
    defaultAdditionalBusinessStatusId: UUID
  ): GqlDeactivateBusinessStatusObjectType!
  deleteWorkshopConnectedLocations(
    locationId: UUID!
    connectedLocationId: UUID
  ): GqlDeleteWorkshopConnectedLocationsObjectType!
  assignLocationWorkshopAppointmentBusinessStatus(
    id: UUID!
    businessStatuses: [GqlAssignLocationWorkshopAppointmentBusinessStatusInputType!]!
  ): GqlAssignLocationWorkshopAppointmentBusinessStatus!
  unassignLocationWorkshopAppointmentBusinessStatus(
    locationId: UUID!
    businessStatusId: UUID!
  ): GqlUnassignLocationWorkshopAppointmentBusinessStatus!
  assignLocationWorkshopAppointmentAdditionalBusinessStatus(
    id: UUID!
    additionalBusinessStatuses: [GqlAssignLocationWorkshopAdditionalAppointmentBusinessStatusInputType!]!
  ): GqlAssignLocationWorkshopAdditionalAppointmentBusinessStatus!
  unassignLocationWorkshopAppointmentAdditionalBusinessStatus(
    locationId: UUID!
    businessStatusId: UUID!
  ): GqlUnassignLocationWorkshopAppointmentAdditionalBusinessStatus!
  updateAvailabilityColors(availabilityColors: [GqlAvailabilityColorWithoutIdInputType!]!): GqlUpdateAvailabilityColor!
  updateLocationOverbooking(
    locationId: UUID!
    capacityOverbookingMultiplier: Float!
    maxCapacityMultiplier: Float!
  ): GqlUpdateLocationOverbookingObjectType!
  updateLocationMinimalOverbooking(
    locationId: UUID!
    minimumOverbookingMultiplier: Float!
  ): GqlUpdateLocationMinimalOverbookingObjectType!
  createWorkshopWork(works: [GqlCreateWorkshopWorkInput!]!): GqlWorkshopWorkObjectType!
  createWorkshopLocationWork(
    locationWorks: [GqlCreateWorkshopLocationWorkInput!]!
  ): GqlCreateWorkshopLocationWorkObjectType!
  updateWorkshopLocationWork(
    locationWork: GqlUpdateWorkshopLocationWorkInput!
  ): GqlUpdateWorkshopLocationWorkObjectType!
  deleteWorkshopLocationWork(id: UUID!): GqlDeleteWorkshopLocationWorkObjectType!
  activateWorkshopWork(id: UUID!): GqlActivateWorkshopWorkObjectType!
  deactivateWorkshopWork(id: UUID!): GqlDeactivateWorkshopWorkObjectType!
  updateLocationCounterReceptionInterval(
    locationId: UUID!
    receptionInterval: Int!
  ): GqlUpdateLocationCounterReceptionIntervalObjectType!
  updateLocationCounterCalendar(
    locationId: UUID!
    workDays: [GqlUpdateLocationCounterCalendarInput!]!
  ): GqlUpdateLocationCounterCalendarObjectType!
  createWorkshopFollowUpWork(
    followUpWork: GqlCreateWorkshopFollowUpWorkInput!
  ): GqlCreateWorkshopFollowUpWorkObjectType!
  updateTeamCapacity(id: UUID!, startDate: String!, capacity: Int!): GqlUpdateTeamCapacityObjectType!
  updateWorkshopFollowUpWork(
    followUpWork: GqlUpdateWorkshopFollowUpWorkInput!
  ): GqlUpdateWorkshopFollowUpWorkObjectType!
}

type GqlUpdateTeamCapacityObjectType {
  status: Boolean!
}

type GqlGetTeamCapacityObjectType {
  teamCapacity: GqlTeamCapacityObjectType!
}

type GqlTeamCapacityObjectType {
  id: String!
  capacity: Int!
  qualificationName: String!
  date: String!
}

type GqlGetLocationTeamsCalendarObjectType {
  locationTeamsCalendar: GqlLocationTeamsCalendarObjectType!
}

type GqlLocationTeamsCalendarObjectType {
  days: [GqlLocationTeamsCalendarDayObjectType!]!
  calendar: GqlLocationTeamsCalendarCalendarObjectType!
}

type GqlLocationTeamsCalendarCalendarObjectType {
  entries: [GqlLocationTeamsCalendarCalendarEntryObjectType!]!
}

type GqlLocationTeamsCalendarDayObjectType {
  date: String
  capacities: [GqlGetLocationTeamsCalendarDayCapacityObjectType!]!
}

type GqlGetLocationTeamsCalendarDayCapacityObjectType {
  teamId: String!
  capacity: Int!
  qualificationName: String!
}

type GqlLocationTeamsCalendarCalendarEntryObjectType {
  id: UUID!
  type: CalendarEntryType!
  isFullDay: Boolean!
  startTime: String
  endTime: String
  startDate: String
  endDate: String
  period: CalendarEntryPeriod
  periodicEnd: String
  isEditable: Boolean!
}

type GqlUpdateLocationCounterCalendarObjectType {
  status: Boolean!
}

input GqlUpdateLocationCounterCalendarBreaksInput {
  startTime: String!
  endTime: String!
}

input GqlUpdateLocationCounterCalendarInput {
  dayNumber: Int!
  startTime: String!
  endTime: String!
  breaks: [GqlUpdateLocationCounterCalendarBreaksInput]!
}

type GqlUpdateLocationCounterReceptionIntervalObjectType {
  status: Boolean!
}

type GqlGetLocationCounterCalendarObjectType {
  workDays: [GqlLocationCounterCalendarObjectType!]!
}

type GqlLocationCounterCalendarBreakObjectType {
  startTime: String!
  endTime: String!
}

type GqlLocationCounterCalendarObjectType {
  dayNumber: Int!
  startTime: String!
  endTime: String!
  breaks: [GqlLocationCounterCalendarBreakObjectType!]!
}

type GqlGetLocationCounterObjectType {
  locationCounter: GqlLocationCounterObjectType!
}

type GqlLocationCounterObjectType {
  id: UUID!
  receptionInterval: Int!
}

type GqlGetWorkshopLocationWorkObjectType {
  id: UUID!
  workId: UUID!
  locationId: UUID!
  isRecommended: Boolean!
  name: String!
  amountPerDayLimit: Int
  capacityPerDayLimit: Float
  brands: [GqlGetWorkshopLocationWorkBrandObjectType!]!
  qualification: GqlGetWorkshopLocationWorkQualificationObjectType!
}

type GqlGetWorkshopLocationWorkBrandObjectType {
  id: UUID!
  name: String!
}

type GqlGetWorkshopLocationWorkQualificationObjectType {
  id: UUID!
  name: String!
}

input GqlUpdateWorkshopLocationWorkInput {
  id: UUID!
  workId: UUID!
  locationId: UUID!
  isRecommended: Boolean!
  amountPerDayLimit: Int
  capacityPerDayLimit: Float
  brands: [GqlUpdateWorkshopLocationWorkBrandInput!]!
}

input GqlUpdateWorkshopLocationWorkBrandInput {
  id: UUID!
}

type GqlUpdateWorkshopLocationWorkObjectType {
  status: Boolean!
}

type GqlDeleteWorkshopLocationWorkObjectType {
  status: Boolean!
}

input GqlCreateWorkshopLocationWorkInput {
  workId: UUID!
  locationId: UUID!
  isRecommended: Boolean!
  amountPerDayLimit: Int
  capacityPerDayLimit: Float
  brands: [GqlCreateWorkshopLocationWorkBrandInput!]!
}

input GqlCreateWorkshopLocationWorkBrandInput {
  id: UUID!
}

type GqlCreateWorkshopLocationWorkObjectType {
  locationWorks: [GqlCreateLocationWorkLocationWorksObjectType!]!
}

type GqlCreateLocationWorkLocationWorksObjectType {
  id: UUID!
}

input GqlCreateWorkshopWorkInput {
  name: String!
  isCapacityEditable: Boolean!
  isDescriptionEditable: Boolean!
  isActive: Boolean!
  qualification: QualificationInput!
  brands: [BrandInput!]!
}

input QualificationInput {
  id: UUID!
}

input BrandInput {
  id: UUID!
  timeUnits: Int!
}

type WorkshopWork {
  id: UUID!
}

type GqlWorkshopWorkObjectType {
  works: [WorkshopWork!]!
}

input GqlUpdateWorkshopFollowUpWorkInput {
  id: UUID!
}

input GqlCreateWorkshopFollowUpWorkInput {
  name: String!
  timeUnits: Int!
  isCapacityEditable: Boolean!
  isDescriptionEditable: Boolean!
  isActive: Boolean!
  qualification: QualificationInput!
}

type WorkshopFollowUpWork {
  id: UUID!
}

type GqlCreateWorkshopFollowUpWorkObjectType {
  id: UUID!
}

type GqlUpdateWorkshopFollowUpWorkObjectType {
  id: UUID!
}

type Customer {
  id: ID!
  name: String!
  username: String!
  email: String!
}

type ServiceAdvisor {
  id: ID!
  name: String!
  username: String!
  email: String!
}

type GqlBusinessStatusObjectType {
  id: UUID!
  name: String!
  isActive: Boolean!
  isDefault: Boolean!
}

type GqlAdditionalBusinessStatusObjectType {
  id: ID!
  name: String!
  isActive: Boolean!
  isDefault: Boolean!
  isHighlighted: Boolean!
}

type GqlConnectedLocationIdObjectType {
  connectedLocationId: ID!
}

type GqlLocationWorkObjectType {
  id: ID!
  locationId: UUID!
  name: String!
  isRecommended: Boolean!
  workId: UUID!
  amountPerDayLimit: Int
  capacityPerDayLimit: Float
  isCapacityEditable: Boolean!
  isDescriptionEditable: Boolean!
  brands: [GqlWorkBrandObjectType!]!
  qualification: GqlWorkQualificationObjectType!
}

type GqlWorkQualificationObjectType {
  id: UUID!
  name: String!
}

type GqlWorkBrandObjectType {
  id: UUID!
  name: String!
  timeUnits: Int!
}

type GqlQualificationObjectType {
  id: UUID!
  code: String!
  name: String!
}

input GqlCreateAdditionalBusinessStatusesInputType {
  name: String!
  isDefault: Boolean!
  isHighlighted: Boolean!
}

input GqlEditAdditionalBusinessStatusInputType {
  id: UUID!
  name: String!
  isDefault: Boolean!
  isHighlighted: Boolean!
}

input GqlAssignLocationWorkshopAppointmentBusinessStatusInputType {
  id: UUID!
}

input GqlAssignLocationWorkshopAdditionalAppointmentBusinessStatusInputType {
  id: UUID!
}

input GqlAvailabilityColorWithoutIdInputType {
  color: String!
  minimalCapacity: Int!
  maximumCapacity: Int
}

type GqlCreateAdditionalBusinessStatusesObjectType {
  status: Boolean!
}

type GqlActivateAdditionalBusinessStatusObjectType {
  status: Boolean!
}

type GqlDeactivateBusinessStatusObjectType {
  status: Boolean!
}

type GqlDeactivateAdditionalBusinessStatusObjectType {
  status: Boolean!
}

type GqlEditAdditionalBusinessStatusObjectType {
  status: Boolean!
}

type GqlGetLocationBusinessStatusesObjectType {
  businessStatuses: [GqlBusinessStatusObjectType!]!
}

type GqlGetAdditionalBusinessStatusesObjectType {
  additionalBusinessStatuses: [GqlAdditionalBusinessStatusObjectType!]!
}

type GqlAssignLocationWorkshopAppointmentBusinessStatus {
  status: Boolean!
}

type GqlUnassignLocationWorkshopAppointmentBusinessStatus {
  status: Boolean!
}

type GqlAssignLocationWorkshopAdditionalAppointmentBusinessStatus {
  status: Boolean!
}

type GqlUnassignLocationWorkshopAppointmentAdditionalBusinessStatus {
  status: Boolean!
}

type GqlAvailabilityColorObjectType {
  id: ID!
  color: String!
  minimalCapacity: Int!
  maximumCapacity: Int
}

type GqlGetAvailabilityColorsObjectType {
  availabilityColors: [GqlAvailabilityColorObjectType!]!
}

type GqlUpdateAvailabilityColor {
  status: Boolean!
}

type GqlActivateWorkshopWorkObjectType {
  status: Boolean!
}

type GqlDeactivateWorkshopWorkObjectType {
  status: Boolean!
}

type GqlDeleteWorkshopConnectedLocationsObjectType {
  status: Boolean!
}

type GqlCreateWorkshopConnectedLocationsObjectType {
  status: Boolean!
}

type GqlGetWorkshopConnectedLocationsObjectType {
  workshopConnectedLocations: [GqlConnectedLocationIdObjectType!]!
}

type GqlUpdateLocationOverbookingObjectType {
  status: Boolean!
}

type GqlUpdateLocationMinimalOverbookingObjectType {
  status: Boolean!
}

type GqlLocationOverbookingObjectType {
  minimumOverbookingMultiplier: Float!
  capacityOverbookingMultiplier: Float!
  maxCapacityMultiplier: Float!
}

type GqlGetLocationOverbookingObjectType {
  locationOverbooking: GqlLocationOverbookingObjectType!
}

type GqlGetLocationWorksObjectType {
  locationWorks: [GqlLocationWorkObjectType!]!
}

type GqlGetQualificationsObjectType {
  qualifications: [GqlQualificationObjectType!]!
}

type GqlGetUserPermissionsObjectType {
  permissions: [GqlPermissionObjectType!]!
}

type GqlPermissionObjectType {
  id: UUID!
  name: String!
  access: [PermissionType!]!
}

enum PermissionType {
  read
  write
}
