scalar UUID

schema {
  query: Query
}

type Query {
  getUserPermissions(id: UUID!): GqlGetUserPermissionsObjectType!
  getWorkshopFollowUpWork(id: UUID!): GqlGetWorkshopFollowUpWorkObjectType!
}

type Customer {
  id: ID!
  name: String!
  username: String!
  email: String!
}

type ServiceAdvisor {
  id: ID!
  name: String!
  username: String!
  email: String!
}

type GqlBusinessStatusObjectType {
  id: UUID!
  name: String!
  isActive: Boolean!
  isDefault: Boolean!
}

type GqlGetUserPermissionsObjectType {
  permissions: [GqlPermissionObjectType!]!
}

type GqlPermissionObjectType {
  id: UUID!
  name: String!
  access: [PermissionType!]!
}

type GqlGetWorkshopFollowUpWorkObjectType {
  id: UUID!
  name: String!
  timeUnits: Float!
  isCapacityEditable: Boolean!
  isDescriptionEditable: Boolean!
  isActive: Boolean!
  qualification: GqlWorkshopFollowUpWorkQualificationObjectType!
}

type GqlWorkshopFollowUpWorkQualificationObjectType {
  id: UUID!
  name: String!
}

enum PermissionType {
  read
  write
}
