extend type Query {
  getLocationServiceAdvisors(locationId: UUID!): GqlGetLocationServiceAdvisorsObjectType!
  getServiceAdvisor(id: UUID!): GqlGetServiceAdvisorObjectType!
  getServiceAdvisorCalendar(id: UUID!, startDate: String!, endDate: String!): GqlGetServiceAdvisorCalendarObjectType!
}

type GqlGetServiceAdvisorCalendarObjectType {
  workDays: [GqlGetServiceAdvisorCalendarWorkDaysObjectType!]!
  calendar: GqlGetServiceAdvisorCalendarEntriesObjectType!
}

type GqlGetServiceAdvisorCalendarEntriesObjectType {
  entries: [GqlGetServiceAdvisorCalendarCalendarEntriesObjectType!]!
}

type GqlGetServiceAdvisorCalendarCalendarEntriesObjectType {
  id: String!
  type: CalendarEntryType!
  isFullDay: Boolean!
  startTime: String
  endTime: String
  startDate: String
  endDate: String
  period: CalendarEntryPeriod!
  periodicEnd: String
  isEditable: Boolean!
}

enum CalendarEntryType {
  ADVISOR_BREAK
  ADVISOR_BUFFER
  ADVISOR_ABSENCE
  PUBLIC_HOLIDAY
}

enum CalendarEntryPeriod {
  NONE
  WEEKLY
}

type GqlGetServiceAdvisorCalendarWorkDaysObjectType {
  date: String!
  startTime: String!
  endTime: String!
}

type GqlGetLocationServiceAdvisorsObjectType {
  serviceAdvisors: [GqlGetServiceAdvisorObjectType!]!
}

type GqlGetServiceAdvisorObjectType {
  id: UUID!
  number: String!
  name: String!
  surname: String!
  receptionInterval: Int!
}
