query GetLocationTeamsCalendar($locationId: UUID!, $startDate: String!, $endDate: String!) {
  getLocationTeamsCalendar(locationId: $locationId, startDate: $startDate, endDate: $endDate) {
    locationTeamsCalendar {
      days {
        date
        capacities {
          teamId
          capacity
          qualificationName
        }
      }
      calendar {
        entries {
          id
          type
          isFullDay
          startTime
          endTime
          startDate
          endDate
          period
          periodicEnd
          isEditable
        }
      }
    }
  }
}

query GetTeamCapacity($id: UUID!, $startDate: String!) {
  getTeamCapacity(id: $id, startDate: $startDate) {
    teamCapacity {
      id
      capacity
      qualificationName
      date
    }
  }
}

mutation UpdateTeamCapacity($id: UUID!, $startDate: String!, $capacity: Int!) {
  updateTeamCapacity(id: $id, startDate: $startDate, capacity: $capacity) {
    status
  }
}
