query GetLocationServiceAdvisors($locationId: UUID!) {
  getLocationServiceAdvisors(locationId: $locationId) {
    serviceAdvisors {
      id
      name
      surname
      number
      receptionInterval
    }
  }
}

query GetServiceAdvisor($id: UUID!) {
  getServiceAdvisor(id: $id) {
    id
    name
    surname
    number
    receptionInterval
  }
}

query GetServiceAdvisorCalendar($id: UUID!, $startDate: DateTime!, $endDate: DateTime!) {
  getServiceAdvisorCalendar(id: $id, startDate: $startDate, endDate: $endDate) {
    workDays {
      date
      startTime
      endTime
    }
    calendar {
      entries {
        id
        type
        isFullDay
        startTime
        endTime
        startDate
        endDate
        period
        periodicEnd
        isEditable
      }
    }
  }
}

mutation UpdateServiceAdvisorCalendarEntry(
  $advisorId: UUID!
  $entryId: UUID!
  $type: String!
  $isFullDay: Boolean!
  $startTime: String
  $endTime: String
  $startDate: String
  $endDate: String
  $period: String!
  $periodicEnd: String
) {
  updateServiceAdvisorCalendarEntry(
    advisorId: $advisorId
    entryId: $entryId
    type: $type
    isFullDay: $isFullDay
    startTime: $startTime
    endTime: $endTime
    startDate: $startDate
    endDate: $endDate
    period: $period
    periodicEnd: $periodicEnd
  ) {
    id
  }
}
