export const WORKSHOP_SCHEDULER_URL = 'https://workshop-scheduler-gateway.nexus.dev/graphql'

export const GRAPHQL_SCHEMAS_PATH = 'src/schemas'

const MOCKED_OPERATIONS_WORKSHOP_SCHEDULER = [
  'GetAdditionalBusinessStatus',
  'GetBusinessStatusesByLocation',
  'GetAdditionalBusinessStatuses',
  'GetAdditionalBusinessStatusesByLocation',
  'CreateAdditionalBusinessStatuses',
  'AssignBusinessStatusesToLocation',
  'UnassignBusinessStatusFromLocation',
  'AssignAdditionalBusinessStatusesToLocation',
  'UnassignAdditionalBusinessStatusFromLocation',
  'UnassignBusinessStatusFromLocation',
  'EditAdditionalBusinessStatus',
  'ActivateAdditionalBusinessStatus',
  'DeactivateAdditionalBusinessStatus',
  'GetAvailabilityColors',
  'UpdateAvailabilityColors',
  'GetWorkshopConnectedLocations',
  'CreateWorkshopConnectedLocations',
  'DeleteWorkshopConnectedLocations',
  'UpdateLocationOverbooking',
  'UpdateLocationMinimalOverbooking',
  'GetLocationOverbooking',
  'GetWorkshopWorks',
  'GetWorkshopFollowUpWorks',
  'CreateWorkshopWork',
  'CreateLocationWork',
  'CreateWorkshopLocationWork',
  'UpdateLocationWork',
  'GetLocationWorks',
  'GetQualifications',
  'UpdateLocationWork',
  'DeleteLocationWork',
  'GetLocationWork',
  'ActivateWorkshopWork',
  'DeactivateWorkshopWork',
  'GetWorkshopWork',
  'GetLocationServiceAdvisors',
  'GetLocationCounter',
  'UpdateLocationCounterReceptionInterval',
  'GetLocationCounterCalendar',
  'UpdateLocationCounterCalendar',
  'GetServiceAdvisorCalendar',
  'GetServiceAdvisor',
  'CreateWorkshopFollowUpWork',
  'GetLocationTeamsCalendar',
  'GetTeamCapacity',
  'UpdateTeamCapacity',
  'UpdateWorkshopFollowUpWork',
  'GetUserPermissions',
]

export const MOCKED_OPERATIONS = [...MOCKED_OPERATIONS_WORKSHOP_SCHEDULER]
