/**
 * TODO:
 * This is a quick fix for typings for resolvers.ts
 *
 * Could also be set upped with the help of graphql-codegen
 * But the resolver typings generated by it are way too complex, and it would be an overkill for a mock server
 */

export type Area = {
  id: string
  name: string
  countryId: string
  addressId: string
  dmsId: string
  crmId: string
  isActive: boolean
}

export type Address = {
  id: string
  postCode: string
  city: string
  address: string
  countryId: string
}

export type Country = {
  id: string
  name: string
}

export type Dms = {
  id: string
  name: string
}

export type Crm = {
  id: string
  name: string
}

export type Location = {
  id: string
  code: string
  name: string
  addressId: string
  areaId: string
  brandIds: [string]
  isActive: boolean
}
