import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  schema: ['../mock-gql-server/src/schemas/**/*.graphql', '!../mock-gql-server/src/schemas/**/technical-admin.graphql'],
  documents: 'src/**/*.graphql',
  hooks: {
    // Fix for Windows (https://github.com/dotansimha/graphql-code-generator/issues/8887)
    afterAllFileWrite: [
      "node -p \"child_process.execSync('prettier --write ' + process.argv.slice(1).map((generatedFilePath) => generatedFilePath.replaceAll(String.fromCharCode('0x5c'), '')).join(' '))\"",
    ],
  },
  config: {
    scalars: {
      UUID: {
        input: 'string',
        output: 'string',
      },
    },
  },
  generates: {
    'src/shared/api/types.generated.ts': {
      plugins: ['typescript'],
    },
    'src/': {
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: 'shared/api/types.generated.ts',
      },
      plugins: [
        {
          add: {
            content: `/* eslint-disable */
            /**
             *
             * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
             *
             * instead, edit one of the \`.graphql\` files in this project and run
             *
             * npm run gql:generate
             *
             * for this file to be re-created
             */`,
          },
        },
        'typescript-operations',
        {
          'typescript-rtk-query': {
            importBaseApiFrom: '@/shared/api',
            importBaseApiAlternateName: 'baseApi',
            exportHooks: true,
          },
        },
      ],
    },
    '.introspection.json': {
      plugins: ['introspection'],
    },
  },
}

export default config
