mutation CreateWorkshopFollowUpWork($workshopFollowUpWork: GqlCreateWorkshopFollowUpWorkInputType!) {
  createWorkshopFollowUpWork(workshopFollowUpWork: $workshopFollowUpWork) {
    id
  }
}

mutation UpdateWorkshopFollowUpWork($workshopFollowUpWork: GqlUpdateWorkshopFollowUpWorkInputType!) {
  updateWorkshopFollowUpWork(workshopFollowUpWork: $workshopFollowUpWork) {
    status
  }
}

query GetWorkshopFollowUpWorks {
  getWorkshopFollowUpWorks {
    works {
      id
      name
      timeUnits
      isCapacityEditable
      isDescriptionEditable
      isActive
      qualification {
        id
        name
      }
    }
  }
}

query GetWorkshopFollowUpWork($id: UUID!) {
  getWorkshopFollowUpWork(id: $id) {
    id
    name
    timeUnits
    isCapacityEditable
    isDescriptionEditable
    isActive
    qualification {
      id
      name
    }
  }
}
