query GetAdditionalBusinessStatuses {
  getWorkshopAppointmentAdditionalBusinessStatuses {
    additionalBusinessStatuses {
      id
      name
      isActive
      isDefault
      isHighlighted
    }
  }
}

query GetAdditionalBusinessStatus($id: UUID!) {
  getWorkshopAppointmentAdditionalBusinessStatus(id: $id) {
    id
    name
    isActive
    isDefault
    isHighlighted
  }
}

mutation CreateAdditionalBusinessStatuses($additionalBusinessStatuses: [GqlCreateAdditionalBusinessStatusInputType!]!) {
  createWorkshopAppointmentAdditionalBusinessStatus(additionalBusinessStatuses: $additionalBusinessStatuses) {
    additionalBusinessStatuses {
      id
    }
  }
}

mutation EditAdditionalBusinessStatus($additionalBusinessStatus: GqlUpdateAdditionalBusinessStatusInputType!) {
  updateWorkshopAppointmentAdditionalBusinessStatus(additionalBusinessStatus: $additionalBusinessStatus) {
    status
  }
}

mutation ActivateAdditionalBusinessStatus($id: UUID!) {
  activateWorkshopAppointmentAdditionalBusinessStatus(id: $id) {
    status
  }
}

mutation DeactivateAdditionalBusinessStatus($id: UUID!, $defaultAdditionalBusinessStatusId: UUID) {
  deactivateWorkshopAppointmentAdditionalBusinessStatus(
    id: $id
    defaultAdditionalBusinessStatusId: $defaultAdditionalBusinessStatusId
  ) {
    status
  }
}

query GetAdditionalBusinessStatusesByLocation($id: UUID!) {
  getLocationWorkshopAppointmentAdditionalBusinessStatuses(id: $id) {
    additionalBusinessStatuses {
      id
      name
      isActive
      isDefault
      isHighlighted
    }
  }
}

mutation AssignAdditionalBusinessStatusesToLocation(
  $locationId: UUID!
  $additionalBusinessStatuses: [GqlAssignLocationAdditionalBusinessStatusesIdsInputType!]!
) {
  assignLocationWorkshopAppointmentAdditionalBusinessStatus(
    locationId: $locationId
    additionalBusinessStatuses: $additionalBusinessStatuses
  ) {
    status
  }
}

mutation UnassignAdditionalBusinessStatusFromLocation($locationId: UUID!, $additionalBusinessStatusId: UUID!) {
  unassignLocationWorkshopAppointmentAdditionalBusinessStatus(
    locationId: $locationId
    additionalBusinessStatusId: $additionalBusinessStatusId
  ) {
    status
  }
}
