mutation CreateLocationWork($locationWorks: [GqlWorkshopLocationWorksInputType!]!) {
  createWorkshopLocationWork(locationWorks: $locationWorks) {
    locationWorks {
      id
    }
  }
}

query GetLocationWorks(
  $filter: GqlWorkshopLocationWorksFilterInputType
  $sort: GqlWorkshopLocationWorksSortInputType
  $offset: Float
  $limit: Float
) {
  getWorkshopLocationWorks(filter: $filter, sort: $sort, offset: $offset, limit: $limit) {
    locationWorks {
      id
      locationId
      name
      isRecommended
      workId
      amountPerDayLimit
      capacityPerDayLimit
      isCapacityEditable
      isDescriptionEditable
      brands {
        id
        code
        timeUnits
      }
      qualification {
        id
        name
      }
    }
  }
}

mutation UpdateLocationWork($workshopLocationWork: GqlUpdateWorkshopLocationWorkInputType!) {
  updateWorkshopLocationWork(workshopLocationWork: $workshopLocationWork) {
    status
  }
}

mutation DeleteLocationWork($id: UUID!) {
  deleteWorkshopLocationWork(id: $id) {
    status
  }
}

query GetLocationWork($id: UUID!) {
  getWorkshopLocationWork(id: $id) {
    id
    workId
    locationId
    isRecommended
    name
    amountPerDayLimit
    capacityPerDayLimit
    brands {
      id
      code
    }
    qualification {
      id
      name
    }
  }
}
